
version: '3.5'

services:



  db:
    image: zeroprg/flask-docker-swarm_db:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    volumes:
      - data-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=streamer

    networks:
      - app


  visualizer:
    image: alexellis2/visualizer-arm:latest
    ports:
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - app

networks:
  app:
    driver: overlay
    ipam:
       driver: default
       config:
           - subnet: 192.168.0.0/16 
volumes:
  data-volume:
    driver: local


