version: '3.5'

services:
   cam:
    image: zeroprg/flask-docker-swarm_cam:latest
#    command: gunicorn --bind 0.0.0.0:3020 manage:app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    ports:
      - 3020:3020
    environment:
      - PORT=3020
      - FLASK_ENV=production
      - APP_SETTINGS=/home/app/web/config.txt
      - DB_IP_ADDRESS=192.168.0.167
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
      #- web
    networks:
      - app


   db:
    image: zeroprg/flask-docker-swarm_db:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
      volumes:
       - data-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - app




   nginx:
    image: zeroprg/flask-docker-swarm_nginx:latest

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
      ports:
      - 80:80
    depends_on:
      - cam
    networks:
      - app

networks:
  app:
    driver: bridge

#volumes:
 # data-volume:
  #  driver: local
