version: '3.5'

services:

  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    image: zeroprg/flask-docker-swarm_web

    expose:
      - 4000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=/home/app/web/config.txt
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SECRET_CODE=myprecious
    depends_on:
      - db
    networks:
      - app

  db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    image: zeroprg/flask-docker-swarm_db

    volumes:
      - data-volume:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - app

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    image: zeroprg/flask-docker-swarm_nginx

    restart: always
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - app


networks:
  app:
    driver: bridge

volumes:
  data-volume:
    driver: local
