version: '3.5'

services:

  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=./services/web/config.txt
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SECRET_CODE=myprecious
    depends_on:
      - db
    networks:
      - app

  db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    volumes:
      - data-volume:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - app


networks:
  app:
    driver: bridge

volumes:
  data-volume:
    driver: local
