version: '3.5'

services:

  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    image: zeroprg/flask-docker-swarm_web:latest
    command: gunicorn --bind 0.0.0.0:4000 manage:app

    ports:
      - 4000:4000 
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=/home/app/web/config.txt
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SECRET_CODE=myprecious
    depends_on:
      - db
    networks:
      - app

  db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    image: zeroprg/flask-docker-swarm_db:latest

    volumes:
      - data-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - app




  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    image: zeroprg/flask-docker-swarm_nginx:latest

    restart: always
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - app


networks:
  app:
    driver: bridge

volumes:
  data-volume:
    driver: local
