version: '3.5'

services:

#  cam:
#    build:
#      context: ./services/cam
#      dockerfile: Dockerfile 
#    image: zeroprg/flask-docker-swarm_cam:latest
#    command: gunicorn --bind 0.0.0.0:3020 manage:app
#    ports:
#      - 3020:3020
#    environment:
#      - FLASK_ENV=production
#      - APP_SETTINGS=/home/app/web/config.txt
#      - DB_USER=postgres
#      - DB_PASSWORD=postgres
#    secrets:
#      - secret_code
#    depends_on:
#      - db
#      - web
#    networks:
#      - app


  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    image: zeroprg/flask-docker-swarm_web:latest
    command: gunicorn --bind 0.0.0.0:4000 manage:app

    ports:
      - 80:4000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=/home/app/web/config.txt
      - DB_USER=postgres
      - DB_IP_ADDRESS=192.168.0.167
      - DB_PASSWORD=postgres
      - SECRET_CODE=myprecious
    depends_on:
      - db
    networks:
      - app

  db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    image: zeroprg/flask-docker-swarm_db:latest
    restart: always
    volumes:
      - data-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - app




#  nginx:
#    build:
#      context: ./services/nginx
#      dockerfile: Dockerfile
#    image: zeroprg/flask-docker-swarm_nginx:latest

#    restart: always
#    ports:
#      - 80:80
#    depends_on:
#      - web
#    networks:
#      - app


networks:
  app:
    driver: bridge

volumes:
  data-volume:
    driver: local
